MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: "ckps/ckp-coco/e2e_mask_rcnn_R_50_FPN_1x_trimmed.pth"
  # WEIGHT: "/mnt/data-disk2/xinting/project/maskrcnn/ckp-coco/e2e_mask_rcnn_R_50_FPN_1x_trimmed.pth"
  
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    FREEZE_CONV_BODY_AT: 2
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.00
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
#     PREDICTOR: "FPNPredictor"
#     FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"

    FEATURE_EXTRACTOR: "FPN2MLPCosineFeatureExtractor"
    PREDICTOR: "FPNCosinePredictor"

    NUM_CLASSES: 271 #copy 81 classes, the 1st one --background
  ROI_MASK_HEAD:
    USE_BBOX2MASK: True
    USE_MLPMASK: False
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  CLS_AGNOSTIC_BBOX_REG: False
  FEW_SHOT:
    ScaleCls: 10
DATASETS:
  # TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  # TEST: ("coco_2014_minival",)
  # TRAIN: ("lvis_v0.5_minival",)
  # TEST: ("lvis_v0.5_minival",)
  TRAIN: ("lvis_v0.5_train_top270",)
  TEST: ("lvis_v0.5_val_top270",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (25000, 35000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 16
  TEST_PERIOD: 3000  #per 2500 step do validation
  CHECKPOINT_PERIOD: 3000
OUTPUT_DIR: "./ckps/ckp-base270_freeze4_set1_balanced"
TENSORBOARD_EXPERIMENT: "./logs-base270_freeze4/logs-base270_freeze4_set1_balanced"